name: coconut_design_system
description: "The Coconut Design System For Coconut Vault/Wallet. Anyone who wants to use this design system is free to do so."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/SpaceGrotesk-Light.ttf
          weight: 300
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard-Regular.ttf
          weight: 400
